### ISSUE TITLE
Redmi K30 安卓13 类原生Bliss-v16.2-phoenix-OFFICIAL-vanilla-20221209卡开机无限重启

### ISSUE THREAD

**Issue by etility** [ozingi/microG_GSync#11]
Redmi K30 安卓13 类原生Bliss-v16.2-phoenix-OFFICIAL-vanilla-20221209

**Comment by ozingi** [comment]
> Redmi K30 安卓13 类原生Bliss-v16.2-phoenix-OFFICIAL-vanilla-20221209

这有点奇怪了，vanilla应该是很干净的，不会冲突，你之前有装过google服务的模块吗？

**Comment by ozingi** [comment]
这有点奇怪了，vanilla应该是很干净的，不会冲突，你之前有装过其他google服务的模块吗？

**Comment by ozingi** [comment]
> Redmi K30 安卓13 类原生Bliss-v16.2-phoenix-OFFICIAL-vanilla-20221209

这有点奇怪了，vanilla应该是很干净的，不会冲突，你之前有装过其他google服务的模块吗？
你可以进rec或者安全模式先把magisk停止，如果是模块的原因就能正常开机了
