### ISSUE TITLE
Android12.1类原生版本提示签名不兼容，无法直接卸载

### ISSUE THREAD

**Issue by TAT-Hins** [ozingi/microG_GSync#6]
机型：一加9Pro
版本：OOS12底包 + Nameless 0711 (LineageOS based)
版本链接：https://forum.xda-developers.com/t/rom-official-oneplus-9-pro-12-1-0_r11-nameless-aosp-2022-07-08.4403301/

问题：
模块clean install的时候提示gms和gsf卸载失败，提示user 0未安装；
安装时报错INSTALL_FAILED_UPDATE_INCOMPATIBLE，提示microg服务框架和已安装版本签名不一致

**Comment by ozingi** [comment]
> 机型：一加9Pro 版本：OOS12底包 + Nameless 0711 (LineageOS based) 版本链接：https://forum.xda-developers.com/t/rom-official-oneplus-9-pro-12-1-0_r11-nameless-aosp-2022-07-08.4403301/
> 
> 问题： 模块clean install的时候提示gms和gsf卸载失败，提示user 0未安装； 安装时报错INSTALL_FAILED_UPDATE_INCOMPATIBLE，提示microg服务框架和已安装版本签名不一致

你可以这样做：
1、干净安装完一遍后重启；
2、重启后再选择覆盖安装一遍看可不可以，如果不行再覆盖安装一遍。
