### ISSUE TITLE
您好，我想知道在面具里移除模块后为什么软件没有卸载掉（？）

### ISSUE THREAD

**Issue by N30E17** [ozingi/microG_GSync#7]
我太蠢了……突然发现移除之后就可以手动删除了，打扰了，麻烦您把这个issue删除掉。

**Comment by ozingi** [comment]
> 或者有什么其余的方法可以删除掉吗

因为这些应用为当前用户安装过一遍，模块卸载后会变成用户应用，你可以搜索“关键字micro”来手动卸载
